--liquibase formatted sql

--changeset dev:001
CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       description TEXT,
                       priority VARCHAR(50) NOT NULL,
                       status VARCHAR(50) NOT NULL DEFAULT 'NEW'
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

INSERT INTO tasks (title, priority, status) VALUES
                                                ('Изучить Liquibase', 'HIGH', 'NEW'),
                                                ('Сравнить с Flyway', 'MEDIUM', 'NEW');

--rollback DROP TABLE tasks;
--rollback DROP TABLE users;